# Generated by Django 5.0.6 on 2024-07-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='can_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='can_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='therapist',
            name='can_login',
            field=models.BooleanField(default=True),
        ),
    ]
