# Generated by Django 5.0.6 on 2024-08-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_parent_can_login_patient_can_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='numuwuser',
            name='can_login',
            field=models.BooleanField(default=False),
        ),
    ]
