# Generated by Django 5.0.6 on 2024-08-01 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_numuwuser_can_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='can_login',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='can_login',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='can_login',
        ),
    ]
