# Generated by Django 5.0.6 on 2024-07-31 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numuw_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
    ]
